name: demv_env
channels:
  - defaults
dependencies:
  - numpy=1.21.5
  - pandas=1.4.1
  - pip=21.2.4
  - python=3.9.12
  - pip:
    - imbalanced-learn==0.9.0
    - imblearn==0.0
    - scikit-learn==1.0.2
    - scipy==1.8.0
