name: demv_env
channels:
  - conda-forge
  - defaults
dependencies:
  - fairlearn=0.7.0
  - numpy=1.21.5
  - pandas=1.4.1
  - python=3.9.12
  - imbalanced-learn==0.9.0
  - scikit-learn==1.0.2
  - scipy==1.8.0